name: 'html-reporter-github-pages'
description: 'Github Pages HTML Test Results with history'
author: 'Pavan Mudigonda'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  token:
    description: 'default Github token'
    required: false
    default: ${{ github.token }}
  workflow_id:
    description: 'Workflow File NAME'
    required: true
    default: ''
  test_results:
    description: 'test result data dir'
    required: true
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  results_history:
    description: 'Folder for allure history'
    required: true
    default: 'results-history'
  subfolder:
    description: 'subfolder'
    required: false
    default: ''
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: '' 
runs:
  using: 'composite'    
  steps:

    - name: Get test results history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: ${{ inputs.gh_pages }}
        path: ${{ inputs.gh_pages }}

    - name: Create Test Results History GitHub Actions Run ID wise
      uses: tr/cicd_gh-actions-gh-pages/history@v1.0
      if: always()
      id: test-results
      with:
        token: ${{ inputs.token }}
        WORKFLOW_ID: ${{ inputs.workflow_id }}
        test_results: ${{ inputs.test_results }}
        gh_pages: ${{ inputs.gh_pages }}
        results_history: ${{ inputs.results_history }}

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ inputs.token }}
        publish_branch: ${{ inputs.gh_pages }}
        publish_dir: ${{ inputs.results_history }}
        keep_files: true
