name: test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: GH Pages Push
        uses: PavanMudigonda/html-reporter-github-pages@v1.0
        with:
          test_results: test-results
          keep_reports: 20
          workflow_id: main.yml
