name: test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: GH Pages Push
        uses: PavanMudigonda/html-reporter-github-pages/composite@v1.1
        with:
          test_results: test-results
          keep_reports: 20
